import { faker } from "@faker-js/faker";

const ROLES = ["Top", "Jungle", "Mid", "Bot", "Support"];
const RESULTS = ["Victory", "Defeat", "Remake"];

/**
 * Generate a single fake match entity
 */
export const generateFakeMatch = () => {
  const durationSeconds = faker.number.int({ min: 60, max: 7200 });

  return {
    champion: faker.helpers.arrayElement([
      "Ahri",
      "Akali",
      "Alistar",
      "Amumu",
      "Anivia",
      "Annie",
      "Aphelios",
      "Ashe",
      "Aurelion Sol",
      "Azir",
      "Bard",
      "Blitzcrank",
      "Brand",
      "Braum",
      "Caitlyn",
      "Camille",
      "Cassiopeia",
      "Cho'Gath",
      "Corki",
      "Darius",
      "Diana",
      "Draven",
      "Dr. Mundo",
      "Ekko",
      "Elise",
      "Evelynn",
      "Ezreal",
      "Fiddlesticks",
      "Fiora",
      "Fizz",
      "Galio",
      "Gangplank",
      "Garen",
      "Gnar",
      "Gragas",
      "Graves",
      "Gwen",
      "Hecarim",
      "Heimerdinger",
      "Hwei",
      "Illaoi",
      "Irelia",
      "Ivern",
      "Janna",
      "Jarvan IV",
      "Jax",
      "Jayce",
      "Jhin",
      "Jinx",
      "K'Sante",
      "Kai'Sa",
      "Kalista",
      "Karma",
      "Karthus",
      "Kassadin",
      "Katarina",
      "Kayle",
      "Kayn",
      "Kennen",
      "Kha'Zix",
      "Kindred",
      "Kled",
      "Kog'Maw",
      "LeBlanc",
      "Lee Sin",
      "Leona",
      "Lillia",
      "Lissandra",
      "Lulu",
      "Lux",
      "Malphite",
      "Malzahar",
      "Maokai",
      "Master Yi",
      "Milio",
      "Miss Fortune",
      "Mordekaiser",
      "Morgana",
      "Naafiri",
      "Nami",
      "Nasus",
      "Nautilus",
      "Neeko",
      "Nidalee",
      "Nilah",
      "Nocturne",
      "Nunu & Willump",
      "Olaf",
      "Orianna",
      "Ornn",
      "Pantheon",
      "Poppy",
      "Pyke",
      "Qiyana",
      "Quinn",
      "Rakan",
      "Rammus",
      "Rang",
      "Rek'Sai",
      "Renata Glasc",
      "Renekton",
      "Rengar",
      "Riven",
      "Rumble",
      "Rune",
      "Ryze",
      "Samira",
      "Sejuani",
      "Senna",
      "Seraphine",
      "Sett",
      "Shaco",
      "Shen",
      "Shyvana",
      "Singed",
      "Sion",
      "Sivir",
      "Skarner",
      "Sona",
      "Soraka",
      "Swain",
      "Sylas",
      "Syndra",
      "Syfen",
      "Tahm Kench",
      "Talon",
      "Taric",
      "Teemo",
      "Tera",
      "Thresh",
      "Thresh",
      "Tristana",
      "Trundle",
      "Tryndamere",
      "Twisted Fate",
      "Twitch",
      "Udyr",
      "Urgot",
      "Urshi",
      "Uta",
      "Varus",
      "Vayne",
      "Veigar",
      "Vel'Koz",
      "Vex",
      "Vi",
      "Viego",
      "Viktor",
      "Vladimir",
      "Volibear",
      "Warwick",
      "Wukong",
      "Xayah",
      "Xerath",
      "Xin Zhao",
      "Yasuo",
      "Yone",
      "Yorick",
      "Young Maokai",
      "Yummi",
      "Yuumi",
      "Zac",
      "Zed",
      "Zeke",
      "Zerath",
      "Zilean",
      "Zoe",
      "Zyra",
    ]),
    role: faker.helpers.arrayElement(ROLES),
    result: faker.helpers.arrayElement(RESULTS),
    kills: faker.number.int({ min: 0, max: 99 }),
    deaths: faker.number.int({ min: 0, max: 99 }),
    assists: faker.number.int({ min: 0, max: 99 }),
    cs: faker.number.int({ min: 0, max: 1500 }),
    visionScore: faker.number.int({ min: 0, max: 300 }),
    duration: durationSeconds,
    date: faker.date.recent({ days: 30 }).toISOString().split("T")[0], // YYYY-MM-DD format
    patch: faker.helpers.arrayElement([
      "14.8",
      "14.9",
      "14.10",
      "14.11",
      "14.12",
      "14.13",
      "14.14",
      "14.15",
      "14.16",
    ]),
    notes: Math.random() > 0.7 ? faker.lorem.sentence() : "", // 30% chance of having notes
  };
};

/**
 * Generate a batch of fake matches
 */
export const generateFakeMatchBatch = (batchSize = 10) => {
  return Array.from({ length: batchSize }, () => generateFakeMatch());
};
